<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Salary_salary</name>
   <tag></tag>
   <elementGuidId>f7c72fa5-84c3-4e29-a0e0-355107e5829c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='salary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;salary&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f0e6148-02cd-4b89-975f-45c017267c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md</value>
      <webElementGuid>a25860af-ecd5-4850-8933-ed8d25da027e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>17832997-0109-40af-9680-e821413c10e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>salary</value>
      <webElementGuid>51d971ce-dc94-46b2-b114-bafc3e906c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Salary</value>
      <webElementGuid>caaeb1b1-dcac-465a-bd90-aa7fe4ae2ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;v_body&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;card flex-fill rCard&quot;]/div[@class=&quot;card-body my-2&quot;]/div[@class=&quot;row rPane&quot;]/div[@class=&quot;col-6 col-md-6 pr2&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-md&quot;]</value>
      <webElementGuid>3ce3046f-f773-41f0-81c7-909462c112d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='salary']</value>
      <webElementGuid>77ce1be7-0571-4de9-b5c8-41395219ff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/div/form/div[2]/div/div/div/div[2]/div/input[6]</value>
      <webElementGuid>05782ec5-83b4-40cc-8d73-5846552ed25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>3cc02a21-ff2d-4190-8c97-2adbc12d8f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'salary' and @placeholder = 'Enter Salary']</value>
      <webElementGuid>de6da5db-573b-41d4-91a7-46f21ef631fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
