<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>72aaf736-1b9b-43a7-9614-e9c5e2f74a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-6-undefined']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-pill.btnRacc.badge.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33f7c7ac-c2cb-41cc-8138-d6376c42a74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-pill btnRacc badge btn-secondary</value>
      <webElementGuid>7fce4e8b-db3d-4f5b-baf8-c8c1a62c1b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1</value>
      <webElementGuid>c170fc83-7b89-4f59-b982-c92c2bbc4fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>02dae0f0-3a2d-4008-9700-8cdf6be4b38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-0&quot;)/div[@id=&quot;cell-6-undefined&quot;]/a[@class=&quot;btn btn-pill btnRacc badge btn-secondary&quot;]</value>
      <webElementGuid>1c0b90aa-9255-403b-89b1-1bb8ba5cb899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-6-undefined']/a</value>
      <webElementGuid>07e93685-7731-4f12-b71e-74e80a114718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>a57c895b-72a2-486f-8d53-0ac0cac54679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 4th 2023'])[1]/following::a[1]</value>
      <webElementGuid>5b45bdd1-fb05-473a-b672-77feffd3666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generated'])[1]/following::a[1]</value>
      <webElementGuid>42ea6557-7517-4d74-af8e-caf1abdc1ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager5'])[1]/preceding::a[1]</value>
      <webElementGuid>c171e087-00b6-419f-beb4-0ab55c6c36f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistant Manager'])[1]/preceding::a[1]</value>
      <webElementGuid>3dc7f2e4-8acc-428c-a0e0-3fd4f3fedb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>1fc2e271-6b8a-48b0-932f-9a99462ab025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1')]</value>
      <webElementGuid>51274689-780a-4536-9c35-d86763d70414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>9d98b0ee-343f-45fa-b866-144fc5f97a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>e5de4025-8985-4d28-910b-77e81eea3897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
