<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>5c5652e2-b96a-4ef3-9103-a756cca6179e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-pill.btnRacc.badge.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-6-undefined']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c49516f6-c83c-4f73-bf19-02b615345c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-pill btnRacc badge btn-secondary</value>
      <webElementGuid>ad20b757-a497-4473-be2d-c54d31072c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1</value>
      <webElementGuid>be45aaa1-aaff-4820-9db8-d834cfdcdf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>fc91d2d0-89ea-4c38-b043-545b485d2131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-0&quot;)/div[@id=&quot;cell-6-undefined&quot;]/a[@class=&quot;btn btn-pill btnRacc badge btn-secondary&quot;]</value>
      <webElementGuid>ae363c49-5775-42f8-bd8e-633c4cd86eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-6-undefined']/a</value>
      <webElementGuid>2e5b74c7-d673-454a-b07d-a93ceeba7e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>dfcb1dfe-9b8b-4c65-9258-681b63294d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 4th 2023'])[1]/following::a[1]</value>
      <webElementGuid>8cf78cff-b993-45a1-84f9-838065acd653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generated'])[1]/following::a[1]</value>
      <webElementGuid>e9872c6b-b8df-41e5-b298-ebc9561592f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager5'])[1]/preceding::a[1]</value>
      <webElementGuid>1e553358-b9d5-466f-b33f-eb8f55cb9e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistant Manager'])[1]/preceding::a[1]</value>
      <webElementGuid>5b989b90-2613-4ad9-8bd3-9acd97adc633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>f6d03203-e75b-44e1-afa6-d70133a7ea71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1')]</value>
      <webElementGuid>455d7214-43f5-4ac6-87b7-0a784b064c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>7209c11b-c5a9-4e58-8076-eb4bd5202147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>ed0beac2-1605-4684-b461-beffd7b8cecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
