<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1.1.1.0Mengarahkan, memonitor dan menga_8fb5c0</name>
   <tag></tag>
   <elementGuidId>851ed868-4d01-4ddd-acce-ba3f75a4a1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/main/div/div[2]/div/div[2]/div/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfd35874-5d67-4ed8-97f5-19b172405470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtitle</value>
      <webElementGuid>fe1f6268-440e-4045-bc8f-d8d4fefb89ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.1.1.0Mengarahkan, memonitor dan menganalisa kegiatan Analisa data kebutuhan suplai produk di Fungsi Supply and Distribution Region</value>
      <webElementGuid>c310aac6-1f82-479f-80a5-4197ac7d848c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;v_body&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card flex-fill rCard&quot;]/div[@class=&quot;card-body my-2&quot;]/div[@class=&quot;rHorOv mb-4&quot;]/div[@class=&quot;card rLvList col-3 mr-2&quot;]/a[@class=&quot;rLvHead rNoDecoLink&quot;]/div[@class=&quot;rtitle&quot;]</value>
      <webElementGuid>b16e21dd-f2d7-4fe0-9870-b85ca3c64713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div[2]/div/div[2]/div/div/a/div</value>
      <webElementGuid>04a758a8-86f1-45a0-88ff-e88152c0949d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/preceding::div[2]</value>
      <webElementGuid>b1a66df8-3ce4-4b00-9951-c34d73735609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mengarahkan, memonitor dan menganalisa kegiatan Analisa data kebutuhan suplai produk di Fungsi Supply and Distribution Region']/parent::*</value>
      <webElementGuid>4d74d3a5-c12b-436b-b099-c8a5bbbc4c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div</value>
      <webElementGuid>485522de-48a6-462c-ab7a-a4d9f566f37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1.1.1.0Mengarahkan, memonitor dan menganalisa kegiatan Analisa data kebutuhan suplai produk di Fungsi Supply and Distribution Region' or . = '1.1.1.0Mengarahkan, memonitor dan menganalisa kegiatan Analisa data kebutuhan suplai produk di Fungsi Supply and Distribution Region')]</value>
      <webElementGuid>954f3001-d864-4f47-b8b3-d140ec2120c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
