<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Change to Parent_addDropdown</name>
   <tag></tag>
   <elementGuidId>ed146c6e-28e6-47a7-b9ff-212043a3ceda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7e3d6fe-8e61-43c4-99b7-00c3f68120f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addDropdown</value>
      <webElementGuid>2ba29904-6de0-4c1d-9eb8-f11e92757396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-pill rTreeAdd dropdown-toggle </value>
      <webElementGuid>7576e070-6b5a-44d7-8ef8-b00f06cb67d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>6d8e09e6-adf2-4d43-b2bc-2cad2ea47997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bcfb3905-798d-4535-af98-0c49a5542072&quot;)/td[4]/div[@class=&quot;btn-group my-1&quot;]/button[@id=&quot;addDropdown&quot;]</value>
      <webElementGuid>176fdd16-2e5c-4795-ad51-b76e45952e3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addDropdown']</value>
      <webElementGuid>6c3bb7b2-cfcd-4404-a25e-70a8161b980e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='bcfb3905-798d-4535-af98-0c49a5542072']/td[4]/div[2]/button</value>
      <webElementGuid>ecbdf492-c19e-4184-acdf-f06b8e9e732a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change to Parent'])[1]/following::button[1]</value>
      <webElementGuid>09e8fcdc-dc5a-4e36-873c-3da1cbe3aba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child of Previous'])[1]/following::button[1]</value>
      <webElementGuid>b71235e8-5c7c-4c87-a7fe-a5b61e8d426f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Next'])[1]/preceding::button[1]</value>
      <webElementGuid>f52125e0-4f35-44ca-b5d4-204c6fb09fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Previous'])[1]/preceding::button[1]</value>
      <webElementGuid>c1338a96-ed17-4b44-886b-1be6d2406889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b79fe5d4-f8b7-4d30-bdc4-a50f5193ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addDropdown']</value>
      <webElementGuid>d8628280-dd7b-4e71-9e97-21ccadd55470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
