<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1_2_3</name>
   <tag></tag>
   <elementGuidId>28af5f73-622d-4bc6-ad29-03980e9d5d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.ql-blank > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='financial']/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0a739879-136a-4ae1-b3a9-05104befff37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financial&quot;)/div[@class=&quot;ql-container ql-snow&quot;]/div[@class=&quot;ql-editor ql-blank&quot;]/p[1]</value>
      <webElementGuid>d16dab95-ea23-4386-a7d9-5a3e113974eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='financial']/div[2]/div/p</value>
      <webElementGuid>32435a27-546a-47f5-b528-b6b34db3e430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial'])[1]/following::p[1]</value>
      <webElementGuid>d3ca4bb1-7a8d-40b1-be55-09ab958a65f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Output'])[1]/following::p[2]</value>
      <webElementGuid>3024fbbd-0b4c-4170-89a5-279ff1570ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Financial'])[1]/preceding::p[1]</value>
      <webElementGuid>fcb06bd8-9eda-4bae-8a1f-044dc215b984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Behaviour Competencies'])[1]/preceding::p[2]</value>
      <webElementGuid>6b453af0-b5b5-421f-9d6f-eb2b2b0981f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/p</value>
      <webElementGuid>9ea6af5a-43e4-4e8c-b772-855d927928d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
