<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>71d5d80e-0ad1-4fc4-a5c0-ef40c4fcc844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-pill.btnRacc.badge.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-6-undefined']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2469cc20-1c4c-4452-88e8-32a323cfd90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-pill btnRacc badge btn-secondary</value>
      <webElementGuid>c721e85c-b4a3-42f8-890e-91dbc1224c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1</value>
      <webElementGuid>8e4e2789-4608-471d-af91-2c41e320867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>a1599a43-9cec-457d-ae24-bb815474b1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-0&quot;)/div[@id=&quot;cell-6-undefined&quot;]/a[@class=&quot;btn btn-pill btnRacc badge btn-secondary&quot;]</value>
      <webElementGuid>d870d896-5940-40dc-9b9d-611952b6769f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-6-undefined']/a</value>
      <webElementGuid>9aef8d8e-c240-404f-bf2b-de79e51a6f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>f5b95cb7-5bbc-4d31-93cd-1bd811c09cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 4th 2023'])[1]/following::a[1]</value>
      <webElementGuid>8d7866cd-aee0-4141-8787-01e1614f85c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generated'])[1]/following::a[1]</value>
      <webElementGuid>e0b76166-b548-4623-8b19-03d18f454cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager5'])[1]/preceding::a[1]</value>
      <webElementGuid>d7141805-3abe-4565-8ee5-903bc4845eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistant Manager'])[1]/preceding::a[1]</value>
      <webElementGuid>86e8d799-3cdc-4ef7-9ad7-0c1978af408c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>1ad81a7b-0685-41c6-a85c-64df5897186b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1')]</value>
      <webElementGuid>7d2859bc-43cb-4be0-84c0-d87d6a782290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>5f8b07ac-3701-4ff9-b239-ac5828fe06dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>9cbf6c56-dc12-40a4-ba8d-0ed190e5174c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
