<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>dd7bb33d-ebec-4f3d-8f25-b27df7a6b705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/main/div[3]/div[5]/center/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4381f6e1-26d1-4203-869d-c18144feb083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>language-toggle</value>
      <webElementGuid>9be2cf0d-b308-4c47-bc0c-cd9819c64e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main h-100 w-100 flex-column my-auto d-flex&quot;]/div[@class=&quot;box-calculate-fte&quot;]/div[@class=&quot;d-flex mx-auto flex-column&quot;]/center[@class=&quot;d-flex my-auto&quot;]/div[@class=&quot;switch&quot;]/label[1]</value>
      <webElementGuid>0f3b351f-c4e0-4b1a-bca7-35f84d373a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[5]/center/div/label</value>
      <webElementGuid>79f409e5-255b-475a-9d46-924f8b74131d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>366fec39-2cf1-439e-b977-43ccdb3b4179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
