<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retype Password_new_password2</name>
   <tag></tag>
   <elementGuidId>c5f771b2-b5e6-4a02-97b4-fd9d3e4d5104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;new_password2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='new_password2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c05c761-5890-4e1c-a77b-2d28800dcc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-md</value>
      <webElementGuid>795f579c-0b5d-4ada-a378-cac22f3874dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a0cc13fd-ab91-49a2-a77d-81a931fb1e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new_password2</value>
      <webElementGuid>f38d1584-ea77-49b3-b7cb-ec63fb6d422c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your new password</value>
      <webElementGuid>bdd35007-acbc-4e45-8d17-b6759f80c934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;v_body&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card flex-fill rCard&quot;]/div[@class=&quot;card-body my-2&quot;]/form[1]/div[@class=&quot;row rPane&quot;]/div[@class=&quot;col-6 col-md-6 pr2&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-md&quot;]</value>
      <webElementGuid>d2a99d1e-62b3-4177-a9a8-2abb68a1130d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='new_password2']</value>
      <webElementGuid>85b8b5b9-7918-4af3-9c3a-aff8322596b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/div/div[2]/div/div/form/div/div[2]/div/div/input[3]</value>
      <webElementGuid>fe56e706-a507-4198-bea3-53915a1890ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>99674d32-3b7f-4f31-a6f7-c7b67c0fe882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'new_password2' and @placeholder = 'Enter your new password']</value>
      <webElementGuid>040d1340-791c-4910-ab42-40944a370686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
