<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahunan_activity_count0c4875a5e-e3fb-_a3fa63</name>
   <tag></tag>
   <elementGuidId>6a620d02-afc6-4532-80e6-1508eecf0197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;activity_count[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='activity_count[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9f15ab5-bc24-4b41-aa92-6884a6373b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c3c25080-482b-4f0f-8ae5-055dee0af1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4ded6f0-4aad-48c7-a821-9af891603e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4283a7c8-2384-41f8-b608-2e4347fc73bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Waktu pengerjaan</value>
      <webElementGuid>dc76aca1-703a-4825-a63d-86dfce3ac0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>activity_count[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]</value>
      <webElementGuid>9d792215-6933-4120-927a-66707af34948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main h-100 w-100 flex-column my-auto d-flex&quot;]/main[@class=&quot;main h-100 w-100&quot;]/div[@class=&quot;col-12 mx-auto h-100&quot;]/div[@class=&quot;row h-100&quot;]/div[@class=&quot;col-sm-10 col-md-12 mx-auto d-table h-100&quot;]/div[@class=&quot;d-table-cell align-middle&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;m-sm-4&quot;]/form[1]/div[@class=&quot;form-group&quot;]/table[@class=&quot;table wla-table rTProcMatrix&quot;]/tbody[1]/tr[4]/td[4]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>fce68445-a2a6-4c60-b51b-4dbd7456c30a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='activity_count[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]']</value>
      <webElementGuid>444f5732-fdcb-4dff-8ffd-e817e4d3174b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div/div/div/div/div[3]/div/div/form/div/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>9260e2ef-6bd6-43e8-9b99-a5897d92c640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input</value>
      <webElementGuid>f70b3683-4ee2-4565-a6a7-21cf812c4558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Input Waktu pengerjaan' and @name = 'activity_count[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]']</value>
      <webElementGuid>d02e029d-8e2d-4505-8219-92f649f76e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
