<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahunan_assessment_time0c4875a5e-e3fb_4911d7</name>
   <tag></tag>
   <elementGuidId>2797acbb-e398-4394-bdaf-6376580d2224</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;assessment_time[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='assessment_time[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddad679b-8e36-42ca-a363-b59db361181a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4e19b518-4008-4875-819a-b64be2757bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b7b6976f-1cf1-4894-a8f3-6c4a47f416fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5cddef97-f56d-4347-9e5f-c7090e330f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Waktu pengerjaan</value>
      <webElementGuid>c37bde0c-9def-427a-a055-4481187f549e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assessment_time[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]</value>
      <webElementGuid>5906abed-0ab9-4958-9425-4cc84844c6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main h-100 w-100 flex-column my-auto d-flex&quot;]/main[@class=&quot;main h-100 w-100&quot;]/div[@class=&quot;col-12 mx-auto h-100&quot;]/div[@class=&quot;row h-100&quot;]/div[@class=&quot;col-sm-10 col-md-12 mx-auto d-table h-100&quot;]/div[@class=&quot;d-table-cell align-middle&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;m-sm-4&quot;]/form[1]/div[@class=&quot;form-group&quot;]/table[@class=&quot;table wla-table rTProcMatrix&quot;]/tbody[1]/tr[4]/td[5]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5c19e6f1-e1e1-4b37-ac1e-2c0bd5818acc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='assessment_time[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]']</value>
      <webElementGuid>4bea6f87-7d22-4c8b-94c5-248f9cbec08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div/div/div/div/div[3]/div/div/form/div/table/tbody/tr[4]/td[5]/input</value>
      <webElementGuid>92ecbacc-ca85-4e3c-b3f4-d23a7ea9ebae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/input</value>
      <webElementGuid>6699cdd0-8ece-4d07-b031-2008c6e04ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Input Waktu pengerjaan' and @name = 'assessment_time[0][c4875a5e-e3fb-466e-9e1a-7d74f457def0][1]']</value>
      <webElementGuid>4e47d120-007d-40a8-9f0b-e0a0c0aafac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
