<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Board NameDescription                  _d80700</name>
   <tag></tag>
   <elementGuidId>132494c3-d806-4665-a627-0d1706d83071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tab-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/main/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>337dbb06-66b4-4800-8f96-fe2095a013f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-content</value>
      <webElementGuid>a9846415-b812-4fea-8a9b-057784025b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Board NameDescription                                      Set As Public BoardSubmitNameSelect options_ReadreadwriteadmininviteadminNeilsya Amstrani Maulidatul Hijriyahneilsyaams0902@gmail.comDelete Member×Delete Member undefined?CancelContinue</value>
      <webElementGuid>edb1b6f4-44d6-476e-bd9b-c8862f433d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;v_body&quot;]/div[1]/main[@class=&quot;content&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;tab tab-vertical&quot;]/div[@class=&quot;tab-content&quot;]</value>
      <webElementGuid>3b392a1f-f205-4205-94bc-17cab37ba6a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div/div/div/div[3]/div</value>
      <webElementGuid>c9aaf3c7-895b-40fd-a98b-705cc0adb95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::div[1]</value>
      <webElementGuid>d7f09491-82bc-4021-88f4-4539b17bd502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[1]</value>
      <webElementGuid>3f115cf0-3cbd-4506-a5d8-85adecb52be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div</value>
      <webElementGuid>9b617ec9-373f-4e29-9a92-82840489586c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Board NameDescription                                      Set As Public BoardSubmitNameSelect options_ReadreadwriteadmininviteadminNeilsya Amstrani Maulidatul Hijriyahneilsyaams0902@gmail.comDelete Member×Delete Member undefined?CancelContinue' or . = 'Board NameDescription                                      Set As Public BoardSubmitNameSelect options_ReadreadwriteadmininviteadminNeilsya Amstrani Maulidatul Hijriyahneilsyaams0902@gmail.comDelete Member×Delete Member undefined?CancelContinue')]</value>
      <webElementGuid>6008d9a8-251b-4c9d-9ce7-b0f2a0e8f41a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
