<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Edit Data_fa fa-plus rTreeCollapse   mr-2</name>
   <tag></tag>
   <elementGuidId>869eadb5-ba56-4727-92ac-6b788650b29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='6f1bad16-7ff2-4a77-ab5d-e32b92b3a0da']/td/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4ef402c6-457e-4018-b7f3-1c1ac9982a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus rTreeCollapse   mr-2 </value>
      <webElementGuid>436c6d2b-c9ab-4362-9d63-e12529f76bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6f1bad16-7ff2-4a77-ab5d-e32b92b3a0da&quot;)/td[1]/div[1]/i[@class=&quot;fa fa-plus rTreeCollapse   mr-2&quot;]</value>
      <webElementGuid>6494acf6-60e0-4bbb-b331-26bcc8977e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='6f1bad16-7ff2-4a77-ab5d-e32b92b3a0da']/td/div/i</value>
      <webElementGuid>35cfb15f-5a92-45d9-95fe-9ceebf6a6102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/i</value>
      <webElementGuid>520d3af6-b175-4b20-b4e9-62a97c083da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
