<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Name cannot empty</name>
   <tag></tag>
   <elementGuidId>85260c41-c1a1-4278-9ae5-0a721a2d1a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vertical-icon-tab-1']/form/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ea5c5f7-9ccc-4a3e-8f5e-55c4a31cdf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>a1df59f8-603f-489f-9af7-18f7f1892c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name cannot empty</value>
      <webElementGuid>5e3f06fa-2f45-419e-9351-0a61267c130b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vertical-icon-tab-1&quot;)/form[1]/div[@class=&quot;form-group&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>8c6c55f3-2539-4838-96d0-eb41c0b1f1b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vertical-icon-tab-1']/form/div/span</value>
      <webElementGuid>66147cd5-c005-4c9c-84f4-78bf27d7e7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board Name'])[1]/following::span[1]</value>
      <webElementGuid>f123ee6d-43ee-40c4-8325-63920e1d3cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::span[1]</value>
      <webElementGuid>2dd8c57a-b277-4d83-ac23-bdadd4e6c64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::span[1]</value>
      <webElementGuid>42d3fc03-ade1-46a2-ad37-0ab77fce134d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set As Public Board'])[1]/preceding::span[12]</value>
      <webElementGuid>f8c68a53-78e5-4c38-9e10-41753f1517f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name cannot empty']/parent::*</value>
      <webElementGuid>99a49435-bee6-4e56-bb63-890d2ac3d9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/span</value>
      <webElementGuid>6d4c0999-6dc2-4b66-bf1e-2be2821b282f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Name cannot empty' or . = 'Name cannot empty')]</value>
      <webElementGuid>bb8f6404-78dd-4bec-b9b4-5ab9f6915785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
