<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1</name>
   <tag></tag>
   <elementGuidId>16352561-6b68-49c9-90c7-94dc46d651ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#objective > div.ql-container.ql-snow > div.ql-editor.ql-blank > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='objective']/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>16d2d860-9330-423a-90f0-7a9e11bbf367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;objective&quot;)/div[@class=&quot;ql-container ql-snow&quot;]/div[@class=&quot;ql-editor ql-blank&quot;]/p[1]</value>
      <webElementGuid>dd8ea972-7b1a-407c-bdbc-2970c71da1b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='objective']/div[2]/div/p</value>
      <webElementGuid>68f46f6e-6e0d-43dd-94d1-1a95010f2ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objective'])[1]/following::p[1]</value>
      <webElementGuid>ddaa72db-186c-48e4-a6ec-3aeccdcf1f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decision'])[1]/following::p[2]</value>
      <webElementGuid>acc3cbb9-908c-44c6-9818-d96918ff9b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Output'])[1]/preceding::p[1]</value>
      <webElementGuid>3257c219-1506-4254-bc6d-4b5ea4f62f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial'])[1]/preceding::p[2]</value>
      <webElementGuid>34890949-310f-4785-a67b-ec73214e8693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/p</value>
      <webElementGuid>62f2ea58-e8d3-4435-abdd-6f7c843ef785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
