<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is Anomaly_is_anomaly</name>
   <tag></tag>
   <elementGuidId>8620a941-031d-4613-aba1-e0b6a12d66ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;is_anomaly&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='is_anomaly']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>590813d8-3b50-4e5f-b8ff-9753ea615957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2d8db963-b61c-46b4-9a8f-73c5c5088e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9be0912d-9f72-42f3-a554-e466f95e178c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_anomaly</value>
      <webElementGuid>bb71452e-76fb-4617-9674-3bba45b1225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1&quot;)/input[@class=&quot;checkbox&quot;]</value>
      <webElementGuid>902b9627-f1ba-4b9f-8cb8-0ef427e39c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='is_anomaly']</value>
      <webElementGuid>c2101f99-dc4f-4a1e-93cb-483f2db149f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='button-1']/input</value>
      <webElementGuid>befe2fd8-40fa-429a-9c05-89d33d836dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div/div/input</value>
      <webElementGuid>3be73633-921e-4a40-97ee-af9ede3d0c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_anomaly']</value>
      <webElementGuid>da7d2cba-3629-4f2d-8432-3a8085c782bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
