<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Board NameDescription                  _53d10b</name>
   <tag></tag>
   <elementGuidId>d39b41e2-ab6f-4c34-a70f-e9becc3e3443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tab-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/main/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a37465d1-5260-457a-8720-d4ae3b6f579a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-content</value>
      <webElementGuid>5b8a64d9-e09c-45f3-affa-ea054c56f9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Board NameDescription                                      Set As Public BoardSubmitNameSelect options_AdminreadwriteadmininviteadminNeilsya Amstrani Maulidatul Hijriyahneilsyaams0902@gmail.comDelete Member×Delete Member undefined?CancelContinue</value>
      <webElementGuid>c3fe35d3-ef9a-491f-9b72-e630132d8a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;v_body&quot;]/div[1]/main[@class=&quot;content&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;tab tab-vertical&quot;]/div[@class=&quot;tab-content&quot;]</value>
      <webElementGuid>bc201f76-5d2c-4451-84ad-b08a3da89c3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div/div/div/div[3]/div</value>
      <webElementGuid>8b2edc1e-0940-4464-93ae-b6bd74d5eb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::div[1]</value>
      <webElementGuid>730cb900-facb-413f-b4b8-6d2be1960d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[1]</value>
      <webElementGuid>e40d234f-21e2-4d4d-8abd-c5dd0d1e11e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div</value>
      <webElementGuid>b087dfcd-cd2e-40e3-8ad8-74f44c58032a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Board NameDescription                                      Set As Public BoardSubmitNameSelect options_AdminreadwriteadmininviteadminNeilsya Amstrani Maulidatul Hijriyahneilsyaams0902@gmail.comDelete Member×Delete Member undefined?CancelContinue' or . = 'Board NameDescription                                      Set As Public BoardSubmitNameSelect options_AdminreadwriteadmininviteadminNeilsya Amstrani Maulidatul Hijriyahneilsyaams0902@gmail.comDelete Member×Delete Member undefined?CancelContinue')]</value>
      <webElementGuid>c3b675da-2cc8-4636-a2d3-8f5ccb9c82b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
