<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan NIK Anda_nik</name>
   <tag></tag>
   <elementGuidId>380718aa-1052-4856-8e44-c403541beb11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nik&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db1f6c29-f7b3-4882-934e-0b05e05b0bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>7f2d9322-9f20-4aef-8b4a-1170dadd5302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eeff6e3d-9fdc-4835-bf32-acf8e2e3e8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>22c7194b-d5d8-48aa-9f89-1a75db21576e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Induk Kepegawaian</value>
      <webElementGuid>36749aba-e61c-4dcb-9080-94daac2a33a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-tab-1&quot;)/input[@class=&quot;form-control form-control-lg&quot;]</value>
      <webElementGuid>aea88c37-0b47-47aa-8e0c-5a7f2e2592fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nik']</value>
      <webElementGuid>543cddf8-0670-4e82-a47e-edc4af539354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-tab-1']/input</value>
      <webElementGuid>a9012379-1026-48d2-9058-86db2e08caca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3d9b47b6-ba25-4a4c-82f4-2bee14eb14cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nik' and @placeholder = 'Nomor Induk Kepegawaian']</value>
      <webElementGuid>1ff7eb77-8268-4347-8b9e-767553f7f794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
