<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Type Name_satu_hari_kerja</name>
   <tag></tag>
   <elementGuidId>d9e486a5-2021-4dcd-96c9-81f668f8607e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;satu_hari_kerja&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='satu_hari_kerja']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94cb2aa1-f3a3-414b-9674-fee2ac405759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2</value>
      <webElementGuid>3c4c0d54-a093-4968-9999-2fe2dab16406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>287c4e29-2aa4-4722-836d-0203d32f4731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>satu_hari_kerja</value>
      <webElementGuid>33290121-d494-464b-8abc-4f0f53d96510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8.0</value>
      <webElementGuid>6b903f92-45b3-4c91-8b76-633dc6fcdc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vertical-icon-tab-3&quot;)/div[@class=&quot;tab&quot;]/div[@class=&quot;tab-content&quot;]/div[@id=&quot;horizontal-icon-tab-1&quot;]/div[@id=&quot;addWTModal&quot;]/div[@class=&quot;modal-sm mx-auto my-auto h-100 d-flex&quot;]/div[@class=&quot;modal-content my-auto&quot;]/form[1]/div[@class=&quot;modal-body m-2&quot;]/input[@class=&quot;form-control mb-2&quot;]</value>
      <webElementGuid>c9ad77c9-c6ee-4090-93e6-ac57db701947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='satu_hari_kerja']</value>
      <webElementGuid>4c7c7f5e-3b80-41a4-91e2-e26753b39381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addWTModal']/div/div/form/div/input[2]</value>
      <webElementGuid>23d9e008-8cfc-4edb-bf92-cdeea9a9b3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>c54bd9d1-1b6a-4f73-a7ea-5908d1cbd0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'satu_hari_kerja']</value>
      <webElementGuid>9ced3c69-67a5-4d37-99ad-aec4f2129006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
