<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Details</name>
   <tag></tag>
   <elementGuidId>edb9e5c8-c3fd-4f7d-8c5e-5d6f56d67c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.boc-chart-menu > div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tree']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a65816c-922f-4c4f-8b45-9c8be20b24c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Details</value>
      <webElementGuid>92edc761-f231-466d-adae-fbef2b11c78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tree&quot;)/div[@class=&quot;boc-chart-menu&quot;]/div[1]/span[1]</value>
      <webElementGuid>24d11d55-905a-4f1c-831e-db450dba1df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tree']/div/div/span</value>
      <webElementGuid>2ec3e233-1456-4122-833e-99a4d3bdca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personel'])[1]/following::span[1]</value>
      <webElementGuid>54698adf-442f-4366-a153-88aa8ae22013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span</value>
      <webElementGuid>7b9b3824-923e-4bc6-a921-934ed9b9c53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  Details' or . = '  Details')]</value>
      <webElementGuid>80305251-0cf3-49da-9f3d-098c81f0ec01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
