<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Print Jobdesc</name>
   <tag></tag>
   <elementGuidId>0b59fc00-9be8-4960-9dbc-3ba5b48ba32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/main/div/div/div/div[2]/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.float-right.btnRacc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9ead399-b082-4e6c-82e1-fdb5231b8c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary float-right btnRacc</value>
      <webElementGuid>bf0fd57d-4515-4fb2-a0c7-e4557fefb5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8dc42520-5404-41ce-a85a-444805cdeeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5dacf8b7-1d17-4cae-9969-dab0ac226056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-desc/print/?id=1.4.9&amp;employee_id=d4e63452-bbe9-462d-a8c4-ac138220d7f6&amp;version_id=81ff44ca-b3fa-4236-a927-22db4fdd4e18&amp;org_id=117936c7-c5ec-46bf-b631-c8a373e18b4a</value>
      <webElementGuid>12b46ef3-2f27-4452-8b18-80d05a2c4911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print Jobdesc</value>
      <webElementGuid>cacf34f7-4265-40e3-b4c0-a2e7e5fc30b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;v_body&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 inline-div&quot;]/div[@class=&quot;col-4 float-right d-flex&quot;]/a[@class=&quot;btn btn-primary float-right btnRacc&quot;]</value>
      <webElementGuid>b7c7e1ae-d26f-4c89-82c5-4da05ad59579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/div/div[2]/div/div[3]/a</value>
      <webElementGuid>454a0012-9271-401c-94ad-2dddd2e5cee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Print Jobdesc')]</value>
      <webElementGuid>38da5cb6-70de-42de-964b-066e2e899da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR Approval'])[1]/following::a[1]</value>
      <webElementGuid>d2ed8773-cde7-4fc3-8a29-84c8b751b7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neilsya Amstrani'])[1]/following::a[1]</value>
      <webElementGuid>383efcbe-bed1-49b5-846b-06fea8356c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/preceding::a[1]</value>
      <webElementGuid>6e871c55-fc6f-4f43-8eeb-79ed8a35aa21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identify &amp; Organization Structure'])[1]/preceding::a[1]</value>
      <webElementGuid>61b6e226-913f-4df4-9ce3-3f7045736908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print Jobdesc']/parent::*</value>
      <webElementGuid>b049a96d-bc1b-4a7c-9eb0-f48c8089fcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job-desc/print/?id=1.4.9&amp;employee_id=d4e63452-bbe9-462d-a8c4-ac138220d7f6&amp;version_id=81ff44ca-b3fa-4236-a927-22db4fdd4e18&amp;org_id=117936c7-c5ec-46bf-b631-c8a373e18b4a')]</value>
      <webElementGuid>cb15ba90-f956-4c4a-9162-8e9ba8ea63e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>7d9dbbd1-9ae6-40c1-aa69-1253dd5b77f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-desc/print/?id=1.4.9&amp;employee_id=d4e63452-bbe9-462d-a8c4-ac138220d7f6&amp;version_id=81ff44ca-b3fa-4236-a927-22db4fdd4e18&amp;org_id=117936c7-c5ec-46bf-b631-c8a373e18b4a' and (text() = 'Print Jobdesc' or . = 'Print Jobdesc')]</value>
      <webElementGuid>e0fe0e77-6d1f-4588-9d9f-245248ad8c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
