<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>d1992f41-b08c-4de8-8e28-8b06a84b864c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-6-undefined']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-pill.btnRacc.badge.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1021d1fa-e058-4d35-9e3c-5d3361161f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-pill btnRacc badge btn-secondary</value>
      <webElementGuid>ac80a936-3b39-4d90-853d-979066a7d906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1</value>
      <webElementGuid>77046c17-c84e-470f-906e-880817c31e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>78c94716-f98b-4ee4-a432-b1febe4f2624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-0&quot;)/div[@id=&quot;cell-6-undefined&quot;]/a[@class=&quot;btn btn-pill btnRacc badge btn-secondary&quot;]</value>
      <webElementGuid>8df416e7-7776-4814-a5ba-b9d519cde0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-6-undefined']/a</value>
      <webElementGuid>ee0f8810-aee6-4f0c-9cd2-ce98eabe2e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>dcc07bfb-d4a1-41bb-9b3d-f0243fb77561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 4th 2023'])[1]/following::a[1]</value>
      <webElementGuid>bcbae190-f7f0-4898-87b4-70b3d2375862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generated'])[1]/following::a[1]</value>
      <webElementGuid>b68da055-983f-4429-b3bf-673dbaa70b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager5'])[1]/preceding::a[1]</value>
      <webElementGuid>fa874bb2-e64a-4114-8543-3f70a9eb73db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistant Manager'])[1]/preceding::a[1]</value>
      <webElementGuid>d539cdb3-ae14-4e41-8975-3c0429d2880b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>2def04cb-f1c8-418d-b8c1-a2f3865e0e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1')]</value>
      <webElementGuid>10282fc1-452d-4739-be72-86d83a76bc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>a3950f78-e1d2-4b8f-ab41-442bbeb05105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/job-desc/detail?tab=1&amp;id=117936c7-c5ec-46bf-b631-c8a373e18b4a&amp;status=1' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>4a0bb5d2-74b3-4394-ae2b-bcf6cfd17635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
